on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

  # Allow manually triggered workflows by maintainers without any
  # parameters to trigger a proactive rebuild (e.g. when a new
  # apko lands)
  workflow_dispatch: {}

name: Create Release

# Don't run multiple releases concurrently.
concurrency: release

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read
      security-events: write # needed for uploading sarif results to github security

    steps:
    - uses: actions/checkout@v3
    - uses: sigstore/cosign-installer@main

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: true
        archs: x86_64,aarch64,armv7

    - uses: strongjz/actions/apko-snapshot@scans
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7

#    # Post to slack when things fail.
#    - if: ${{ failure() }}
#      uses: rtCamp/action-slack-notify@v2.2.0
#      env:
#        SLACK_ICON: http://github.com/chainguardian.png?size=48
#        SLACK_USERNAME: chainguardian
#        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#        SLACK_CHANNEL: distroless
#        SLACK_COLOR: '#8E1600'
#        MSG_MINIMAL: 'true'
#        SLACK_TITLE: Releasing ${{ github.repository }} failed.
#        SLACK_MESSAGE: |
#          For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
